services:
  backend:
    build:
      context: ./calliope-backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./calliope-backend:/app
      #- /app/node_modules
    env_file:
      - ./calliope-backend/.env

  client:
    build:
      context: ./calliope-client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./calliope-client:/app
      # - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000

  ai:
    build:
      context: ./calliope-ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./calliope-ai:/app
    environment:
      - PYTHONUNBUFFERED=1
