services:
  backend:
    build:
      context: ./calliope-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./calliope-backend:/app
      - /app/node_modules
    env_file:
      - ./calliope-backend/.env.prod

  client:
    build:
      context: ./calliope-client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./calliope-client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000

  ai:
    build:
      context: ./calliope-ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./calliope-ai:/app
    environment:
      - PYTHONUNBUFFERED=1

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ./calliope-db/.env
    volumes:
      - calliope-db:/var/lib/postgresql/data
      - ./calliope-db/init-scripts:/docker-entrypoint-initdb.d

volumes:
  calliope-db:
