services:
  backend:
    build:
      context: ./calliope-backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./calliope-backend:/app
      - /app/node_modules
    env_file:
      - ./calliope-backend/.env

  client:
    build:
      context: ./calliope-client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway" # Spécifiquement pour Linux
    volumes:
      - /app/node_modules
      - ./calliope-client:/app
    environment:
        - NODE_ENV=development

  ai:
    build:
      context: ./calliope-ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./calliope-ai:/app
    environment:
      - PYTHONUNBUFFERED=1
