name: CI Pipeline

on:
  push:
    branches:
      - main  # ou la branche sur laquelle tu veux que l'action se déclenche
  pull_request:
    branches:
      - main  # ou la branche sur laquelle tu veux que l'action se déclenche

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5000:5000
          - 5173:5173
          - 8000:8000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install make
        run: sudo apt-get install make

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set environment variables for Docker
        run: |
          echo "NODE_ENV=production" >> calliope-backend/.env
          echo "DATABASE_URL=your_database_url" >> calliope-backend/.env 

      # Construire et démarrer les conteneurs avec Make
      - name: Build and start containers
        run: make docker-up

      - name: Install dependencies
        run: docker compose run --rm backend npm install

      - name: Verify Jest installation
        run: docker compose run --rm backend npm list jest


      # Exécuter les tests avec Make
      - name: Run tests
        run: make tests

      # Optionnellement, arrêter les conteneurs
      - name: Stop containers
        run: make docker-down
