name: CI Pipeline

on:
  push:
    branches:
      - main  # ou la branche sur laquelle tu veux que l'action se déclenche
  pull_request:
    branches:
      - main  # ou la branche sur laquelle tu veux que l'action se déclenche

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5000:5000
          - 5173:5173
          - 8000:8000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install make
        run: sudo apt-get install make

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Construire et démarrer les conteneurs avec Make
      - name: Build and start containers
        run: make docker-up

      # Exécuter les tests avec Make
      - name: Run tests
        run: make tests

      # Afficher les logs
      - name: Display logs
        run: make docker-logs

      # Optionnellement, arrêter les conteneurs
      - name: Stop containers
        run: make docker-down
