name: CI Pipeline

on:
  push:
    branches:
      - main # ou la branche sur laquelle tu veux que l'action se déclenche
      - development
  pull_request:
    branches:
      - main # ou la branche sur laquelle tu veux que l'action se déclenche
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5000:5000
          - 5173:5173
          - 8000:8000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install make
        run: sudo apt-get install make

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set environment variables for Docker
        run: |
          echo "NODE_ENV=development" >> calliope-backend/.env
          echo "DATABASE_URL=your_database_url" >> calliope-backend/.env

      - name: Build and start containers
        run: make docker-up # On démarre les conteneurs avec Make

  test:
    runs-on: ubuntu-latest
    needs: build # Attendre que le job "build" soit terminé avant de commencer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install make
        run: sudo apt-get install make

      - name: Create .env file
        run: |
          echo "NODE_ENV=development" > calliope-backend/.env
          echo "DATABASE_URL=your_database_url" >> calliope-backend/.env
          # Ajoute toutes les autres variables d'environnement nécessaires à ton projet

      - name: Run tests
        run: make tests # Exécuter les tests dans les conteneurs Docker

      - name: Stop containers
        run: make docker-down # Arrêter les conteneurs après les tests
